.TH "main.c" 3 "20 Apr 2010" "Version 0.2" "BNG Bootloader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'storage/persistent.h'\fP
.br
\fC#include 'storage/volatile.h'\fP
.br
\fC#include 'io/serial.h'\fP
.br
\fC#include 'configuration/registry.h'\fP
.br
\fC#include 'commands/registry.h'\fP
.br
\fC#include '../storage/persistent.h'\fP
.br
\fC#include '../storage/volatile.h'\fP
.br
\fC#include '../configuration/registry.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char * argv[])"
.PP
Definition at line 60 of file main.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for BNG Bootloader from the source code.
